# version: '3.9'

services:

  # 1) PHP-FPM (Laravel App)

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: booking_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - frontend_assets:/var/www/html/public
    env_file:
      - ./.env
    networks:
      - booking_net
    environment:
      APP_KEY: ${APP_KEY}
      CACHE_DRIVER: file
      SESSION_DRIVER: file


  # 2) Nginx Web Server
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: booking_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - booking_net


  # 3) MySQL Database
  db:
    image: mysql:8
    container_name: booking_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: booking
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - booking_net


  # 4) Node Builder (for frontend assets)
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: booking_node
    working_dir: /var/www/html
    volumes:
      - frontend_assets:/app/public
    networks:
      - booking_net

# Networks + Volumes
networks:
  booking_net:
    driver: bridge

volumes:
  mysql_data:
  frontend_assets:

